# Generated by Django 3.1.7 on 2021-03-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0)),
                ('initial_time', models.TimeField()),
                ('final_time', models.TimeField()),
                ('vol', models.IntegerField(choices=[(0, '0%'), (1, '25%'), (2, '50%'), (3, '75%'), (4, '100%')], default=3)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='controle.music')),
            ],
        ),
    ]
